from transformers import BertModel, BertTokenizer, BertForSequenceClassification

tokeniser = BertTokenizer.from_pretrained("./", do_lower_case=False)
model = BertForSequenceClassification.from_pretrained('HIC-1/', num_labels=1)

# heavy chain sequences
sequences_heavy = [
    "QVQLQQSGGELAKPGASVKVSCKASGYTFSSFWMHWVRQAPGQGLEWIGYINPRSGYTEYNEIFRDKATMTTDTSTSTAYMELSSLRSEDTAVYYCASFLGRGAMDYWGQGTTVTVSS",
    "QVQLVQSGAEVKKPGASVKVSCKASGYTFTSYWMHWVRQAPGQGLEWMGMIHPQSGSTNYIEKFKSRVTLTVDKSTSTAYMELSSLRSEDTAVYYCARWGFWTGTDYWGQGTLVTVSS"  #1.545 1.362
]

# light chain sequences
sequences_light = [
    "DIQMTQSPSSLSASVGDRVTITCRASQDISNYLAWYQQKPGKAPKLLIYYTSKIHSGVPSRFSGSGSGTDYTFTISSLQPEDIATYYCQQGNTFPYTFGQGTKVEIK",
    "DIQMTQSPSFLSASVGDRVTITCKASQNVGTAVAWYQQKPGKAPKLLIYSTSNRYTGVPSRFSGSGSGTDFTLTISSLQPEDFATYFCQQYSSYPLTFGQGTKLEIK"
]

# The tokeniser expects input of the form ["V Q ... S S [SEP] E V ... I K", ...] #9.2
paired_sequences = []
for sequence_heavy, sequence_light in zip(sequences_heavy, sequences_light):
    paired_sequences.append(' '.join(sequence_heavy)+' [SEP] '+' '.join(sequence_light))

tokens = tokeniser.batch_encode_plus(
    paired_sequences, 
    add_special_tokens=True, 
    pad_to_max_length=True, 
    return_tensors="pt",
    return_special_tokens_mask=True
)
#Note that the tokeniser adds a [CLS] token at the beginning of each paired sequence, a [SEP] token at the end of each paired sequence and pads using the [PAD] token. For example a batch containing sequences V Q L [SEP] E V V, Q V [SEP] A L will be tokenised to [CLS] V Q L [SEP] E V V [SEP] and [CLS] Q V [SEP] A L [SEP] [PAD] [PAD].
#Sequence embeddings are generated by feeding tokens through the model

output = model(
    input_ids=tokens['input_ids'], 
    attention_mask=tokens['attention_mask']
)

print(output.logits)
